month_dictionary = {
    1: "Jan",
    2: "Feb",
    3: "Mar",
    4: "Apr",
    5: "May",
    6: "Jun",
    7: "Jul",
    8: "Aug",
    9: "Sep",
    10: "Oct",
    11: "Nov",
    12: "Dec",
}

non_working_days = {
    2021: {
        1: [{'day': 1,
             'cups': None,
             'campuses': None},
            {'day': 3,
             'cups': None,
             'campuses': None},
            {'day': 4,
             'cups': None,
             'campuses': None},
            {'day': 5,
             'cups': None,
             'campuses': None},
            {'day': 6,
             'cups': None,
             'campuses': None},
            {'day': 23,
             'cups': None,
             'campuses': ['TO']},
            {'day': 28,
             'cups': None,
             'campuses': ['CU']},
            {'day': 29,
             'cups': None,
             'campuses': None},
            ],
        2: [],
        3: [
            {'day': 29,
             'cups': None,
             'campuses': None},
            {'day': 30,
             'cups': None,
             'campuses': None},
            {'day': 31,
             'cups': None,
             'campuses': None},
        ],
        4: [
            {'day': 1,
             'cups': None,
             'campuses': None},
            {'day': 2,
             'cups': None,
             'campuses': None},
            {'day': 5,
             'cups': None,
             'campuses': ['TO']},
        ],
        5: [
            {'day': 1,
             'cups': None,
             'campuses': None},
            {'day': 24,
             'cups': None,
             'campuses': ['CR']},
            {'day': 28,
             'cups': None,
             'campuses': ['CU']},
            {'day': 31,
             'cups': None,
             'campuses': None},
        ],
        6: [
            {'day': 1,
             'cups': None,
             'campuses': ['CU']},
            {'day': 3,
             'cups': None,
             'campuses': None},
            {'day': 4,
             'cups': None,
             'campuses': ['AB', 'CR', 'TO']},
            {'day': 24,
             'cups': None,
             'campuses': None},
        ],
        7: [
            {'day': 30,
             'cups': None,
             'campuses': ['CR']},
        ],
        8: [
            {'day': x, 'cups': None, 'campuses': None} for x in range(9, 23)
        ],
        9: [
            {'day': 8,
             'cups': None,
             'campuses': ['AB']},
            {'day': 21,
             'cups': None,
             'campuses': ['CU']},
        ],
        10: [
            {'day': 12,
             'cups': None,
             'campuses': None},
        ],
        11: [
            {'day': 1,
             'cups': None,
             'campuses': None},
        ],
        12: [
                {'day': x, 'cups': None, 'campuses': None} for x in range(24, 32)
            ] +
            [
                {'day': 6,
                 'cups': None,
                 'campuses': None},
                {'day': 8,
                 'cups': None,
                 'campuses': None}
            ]
    },
}
